pipeline {
    agent any

    tools {
        jdk 'jdk-21'
        // Install the Maven version configured as "M3" and add it to the path.
        maven "jenkins-maven"
    }

    stages {
        stage('Checkout') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/jenkins-docs/simple-java-maven-app.git'

            }
        }
        stage('Build') {
                steps {
                    // Run Maven on a Unix agent.
                    sh 'mvn -B clean package'
                }
            }
            stage('Test') {
                steps {
                    // Run Maven on a Unix agent.
                    sh 'mvn test'
                }
                post {
                    // Archive the test results.
                    always {
                        junit '**/target/surefire-reports/*.xml'
                    }
                }
            }
            stage('Deploy') {
                steps {
                    // Run Maven on a Unix agent.
                    sh 'echo deployed'
                }
            }
    }

    post{
        failure {
            // Send a notification if the build fails
            mail to: 'davjasdeepsinghji9e17@gmail.com',
                 subject: "Build failed in Jenkins: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Something is wrong with the build. Please check the console output at ${env.BUILD_URL}"
        }
        success {
            // Send a notification if the build succeeds
            echo 'Build succeeded!'
            archiveArtifacts artifacts: '**/target/*.jar', onlyIfSuccessful: true
        }
    
    }
}
